name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "fake" 
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "fake"
  CLERK_SECRET_KEY: "fake"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
