name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "fake" 
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "fake"
  CLERK_SECRET_KEY: "fake"
  TMDB_API_KEY: "fake"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
